version: "3"
services:
  go_manual:
    build:
      context: .
    container_name: cube_go_manual_manual
    environment:
      - OTEL_SERVICE_NAME=cube_sample_go_manual
      - OTEL_EXPORTER_OTLP_COMPRESSION=gzip

      # print traces on console
      - OTEL_LOG_LEVEL=debug
      # send traces to CubeAPM
      # - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://host.docker.internal:4318/v1/traces
